version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/cohorts
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input.csv


  plot_stppop_bar:
    run: r:latest analysis/basic_plot_script.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        figure1: output/plots/plot_stppop_bar.png

  plot_stppop_map:
    run: r:latest analysis/basic_map_plot_script.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/cohorts/stppop_map.csv
