version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/cohorts
    outputs:
      highly_sensitive:
        cohort: output/input_cohort.csv


  plot_stppop:
    run: r:latest analysis/plot_stppop.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        figure1: output/plots/plot_stppop_bar.png

